# Generated by Django 3.0.5 on 2023-12-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20231209_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assignedDoctorId',
        ),
    ]
